import "bootstrap/dist/css/bootstrap.min.css";
import React from "react";
import Navbar from "../../Components/Navbar";
import styles from "../../styles/listings.module.css";
import Searchbar from "../../Components/Searchbar";
import Head from "next/head";
import Card from "../Card";
import { useUser } from "@auth0/nextjs-auth0";

// import GiveAwayModal from "../Components/GiveAwayModal/index";

// PLAN
// set up getStaticprops
// make a fetch GET request to https://it-crowd-project.herokuapp.com/api/items
// retur props, items: data
// destructure items array
// map over the array  and for each render </card> with database details dynamically updated
// pass down props into card component; item_id, user_id, category, item_name, item_description, use_by_date, date_added, quantity, cloudinary_id, is_reserved, availability, time_slot

function ListingsPage({ users, listings }) {

	const { user, error, isLoading } = useUser();

  // console.log(u)
  // console.log(users.);

  if (isLoading) return <div>Loading ...</div>;
  if (error) return <div>{error.message}</div>;

  const regUser = users.find((regUser) => regUser.email === user.email);

  console.log(regUser);

  return (
    <>
      <Head>
        <title>iGive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
        </style>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
   	<Navbar avatar={!regUser ? user.picture : regUser.avatar} users={users} />
      <div className={styles.searchbar}>
        <Searchbar />
      </div>
      <div className={styles.container}>
        {/* mapping over our fetch GET request from users and items database table, to render each item on listinngs page */}
        {listings.map((listing) => (
          <div key={listing.item_id}>
            <Card
              item_id={listing.id}
              user_id={listing.user_id}
              first_name={listing.first_name}
              last_name={listing.last_name}
              email={listing.email}
              address={listing.address}
              is_active={listing.is_active}
              category={listing.category}
              item_name={listing.item_name}
              item_description={listing.item_description}
              use_by_date={listing.use_by_date}
              date_added={listing.date_added}
              quantity={listing.quantity}
              item_image={listing.item_image}
              is_reserved={listing.is_reserved}
              availability={listing.availability}
              time_slot={listing.time_slot}
              cloudinary_id={listing.cloudinary_id}
              avatar={listing.avatar}
              user_bio={listing.user_bio}
            />
          </div>
        ))}
        ;
      </div>
    </>
  );
}
export default ListingsPage;
