import Head from "next/head";
import Image from "next/image";
import Card from "../Components/Card/index";
import Navbar from "../Components/Navbar/index";
import styles from "../styles/home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";

import {
	Top,
	Middle,
	Bottom,
	VeryBottom,
} from "../Components/LandingPageComps/landingPageComps.js";
import { withPageAuthRequired } from "@auth0/nextjs-auth0/dist/frontend";

export default function Home() {
	return (
		<div>
			<Head>
				<title>iGive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
				></link>
			</Head>
			<Navbar />

			<div className={styles.container}>
				<Top />
				<main className={styles.main}>
					{/* {user ? <Reg/> : <List/>} */}
					<Middle />
					<Bottom />
					<VeryBottom />
					<div className={styles.footer}>
						<a href="#" className={styles.btn_up}>
							Pop Up
						</a>
						<p className={styles.cast}>
							created by <strong>IT-Crowd</strong>
							<br /> Simren, Lilly-Ane, Irfan, Thuan, Rory, Dmitriy
						</p>
					</div>
				</main>
			</div>
		</div>
	);
}

export const getServerSideProps = withPageAuthRequired();
