import { useUser } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Image from "next/image";
import Card from "../Components/Card/index";
import Navbar from "../Components/Navbar/index";

import styles from "../styles/home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";

import {
	Top,
	Middle,
	Bottom,
	VeryBottom,
} from "../Components/LandingPageComps/landingPageComps.js";

export default function Home({ users }) {
	const { user, error, isLoading } = useUser();
	if (isLoading) return <div>Loading ...</div>;
	if (error) return <div>{error.message}</div>;
	console.log(user);

	const regUser = users.find((rUser) => rUser.email === user?.email);

	return (
		<div>
			<Head>
				<title>iGive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
				></link>
			</Head>
			{/* when visiting the site for the first time, this component won't try and extract user data from auth0 that doesn't yet exist until after login (e.g. user.picture undefined on mount) */}

			<Navbar
				avatar={!regUser ? user?.picture : regUser.avatar}
				users={users}
			/>

			<div className={styles.container}>
				<Top />
				<main className={styles.main}>
					<Middle />
					<Bottom />
					<VeryBottom />
					<div className={styles.footer}>
						<a href="#" className={styles.btn_up}>
							Pop Up
						</a>
						<p className={styles.cast}>
							created by <strong>IT-Crowd</strong>
							<br /> Simren, Lilly-Ane, Irfan, Thuan, Rory, Dmitriy
						</p>
					</div>
				</main>
			</div>
		</div>
	);
}

export const getServerSideProps = async () => {
	const usersRes = await fetch(
		`https://it-crowd-project.herokuapp.com/api/users`
	);
	const usersData = await usersRes.json();

	return {
		props: { users: usersData.payload },
	};
};
