import React from "react";
import Card from "../Components/Card/index";
import Navbar from "../Components/Navbar/index.js";
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../styles/listings.module.css";
import Searchbar from "../Components/Searchbar";
import Head from "next/head";

function Listings() {
	return (
		<>
			<Head>
				<title>iGive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<style>
					@import
					url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
				</style>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
				></link>
			</Head>

			<Navbar />
			<div className={styles.searchbar}>
				<Searchbar />
			</div>
			<div className={styles.container}>
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
				<Card />
			</div>
		</>
	);
}

export default Listings;
