import React from "react";
import Card from "../Components/Card/index";
import Navbar from "../Components/Navbar/index.js";
import styles from "../styles/profile.module.css";
import Link from "next/link";
import Head from "next/head";
import Button from "../Components/Button";

function profile() {
  return (
    <div className="main-container">
      <Head>
        <title>iGive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
        </style>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <Navbar />

      <div className={styles.form}>
        <form></form>
      </div>

      <div className={styles.flexboxContainer}>
        <div className={`${styles.flexItems} ${styles.flexItem1}`}>
          <div className={styles.userImg}>
            <Link href="/">
              <a>
                <img src="https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" />
              </a>
            </Link>
            <span className={`fa fa-camera ${styles.camera}`}></span>
            <div className={styles.stars}>
              <span className={`fa fa-star ${styles.checked}`}></span>
              <span className={`fa fa-star ${styles.checked}`}></span>
              <span className={`fa fa-star ${styles.checked}`}></span>
              <span className={`fa fa-star ${styles.checked}`}></span>
              <span class="fa fa-star"></span>
            </div>
          </div>
        </div>

        <div className={`${styles.flexItems} ${styles.flexItem2}`}>
          <div className={styles.profileInfoBox}>
            <div className={styles.block1}>
              <h4 className={styles.profileTitle}>Name</h4>
              <h5 className={styles.infoLine}>Boris Johnson</h5>
            </div>
            <div className={styles.block2}>
              <h4 className={styles.profileTitle}>Address</h4>
              <h5 className={styles.infoLine}>10 Downing Street, London</h5>
            </div>
            <div className={styles.block3}>
              <h4 className={styles.profileTitle}>Email</h4>
              <h5 className={styles.infoLine}>Boris@gmail.com</h5>
            </div>
            <div className={styles.block4}>
              <h4 className={styles.profileTitle}>Number</h4>
              <h5 className={styles.infoLine}>07467893993</h5>
            </div>
            <button className={styles.editBtn}>Edit</button>
          </div>
        </div>
        <div className={`${styles.flexItems} ${styles.flexItem4}`}>
          <h4 className={styles.profileTitle}>Bio</h4>
        </div>
        <div className={styles.btnSection}>
          <button className={styles.giveBtn}>Give Item</button>
          <button className={styles.searchBtn}>Search Item</button>
        </div>

        <h2 className={styles.title}>My Listing</h2>

        <div className={`${styles.flexItems} ${styles.flexItem3}`}>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </div>
    </div>
  );
}

export default profile;
