import React from "react";
import Card from "../Components/Card/index";
import Navbar from "../Components/Navbar/index.js";
import styles from "../styles/profile.module.css";
import Link from "next/link";
import Head from "next/head";
import Button from "../Components/Button";

function profile() {
  return (
    <div className="main-container">
      <Head>
        <title>iGive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
        </style>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <Navbar />

      <div className={styles.form}>
        <form></form>
      </div>

      <div className={styles.flexboxContainer}>
        <div className={`${styles.flexItems} ${styles.flexItem1}`}>
          <div className={styles.userImg}>
            <Link href="/">
              <a>
                <img src="https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" />
              </a>
            </Link>
          </div>
          <span className={`fa fa-camera ${styles.camera}`}></span>
          <div className={styles.stars}>
            <span className={`fa fa-star ${styles.checked}`}></span>
            <span className={`fa fa-star ${styles.checked}`}></span>
            <span className={`fa fa-star ${styles.checked}`}></span>
            <span className={`fa fa-star ${styles.checked}`}></span>
            <span class="fa fa-star"></span>
          </div>
        </div>
        <div className={`${styles.flexItems} ${styles.flexItem2}`}>
          <form>
            <div className={styles.box1}>
              <label className={styles.profileTitle}>Name</label>
              <input
                className={styles.input}
                type="text"
                placeholder="Boris Johnson"
              ></input>
              <label className={styles.profileTitle}>Address</label>
              <input
                className={styles.input}
                type="text"
                placeholder="10 Downing Street, London"
              ></input>
              <label className={styles.profileTitle}>Email</label>
              <input
                className={styles.input}
                type="text"
                placeholder="Boris@gmail.com"
              ></input>
              <label className={styles.profileTitle}>Number</label>
              <input
                className={styles.input}
                type="number"
                placeholder="07476052989"
              ></input>
            </div>
            <div className={styles.box2}></div>
          </form>
        </div>

        <div className={`${styles.flexItems} ${styles.flexItem3}`}>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </div>
    </div>
  );
}

export default profile;
