import React from "react";
import Navbar from "../Components/Navbar/index.js";
import styles from "../styles/register.module.css";
import Button from "../Components/Button/index.js";

function Register() {
	return (
		<>
			<Head>
				<title>iGive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<style>
					@import
					url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
				</style>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
				></link>
			</Head>

			<Navbar />
			<div className={styles.container}>
				<h1>Fill in your details below...</h1>
				<div className={styles.form}>
					<form>
						<label className={styles.label}>First Name</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your first name..."
						></textarea>
						<label className={styles.label}>Last Name</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your last name..."
						></textarea>
						<label className={styles.label}>Address</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your address..."
						></textarea>
						<label className={styles.label}>Contact Number</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your contact number..."
						></textarea>
						<label className={styles.label}>Email</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your email..."
						></textarea>
					</form>
					<Button text="Submit" />
				</div>
			</div>
		</>
	);
}

export default Register;
