import React from "react";
import Navbar from "../Components/Navbar/index.js";
import styles from "../styles/register.module.css";
import Button from "../Components/Button/index.js";
import Head from "next/head";
import { useState } from "react";

function Register() {
	//capture form data
	const [previewSource, setPreviewSource] = useState("");
	const [firstName, setFirstName] = useState("");
	const [address, setAddress] = useState("");
	const [email, setEmail] = useState("");
	const [lastName, setLastName] = useState("");

	//an object which will represent the form data to send to the server (req.body)
	const body = {
		first_name: firstName,
		last_name: lastName,
		email: email,
		address: address,
		is_active: true,
		image: previewSource,
		user_bio: "",
	};

	//when the user selects an image from their desktop, preview it in the browser
	const handleFileInputChange = (e) => {
		const file = e.target.files[0];
		previewFile(file);
	};

	//convert to base64encoded image using new FileReader API
	const previewFile = (file) => {
		const reader = new FileReader();
		reader.readAsDataURL(file);

		reader.onloadend = () => {
			setPreviewSource(reader.result);
		};
	};

	//stringify the body object defined above and send as req.body to server
	const handleSubmit = async () => {
		await fetch(`https://it-crowd-project.herokuapp.com/api/users`, {
			method: "POST",
			body: JSON.stringify(body),
			headers: { "Content-Type": "application/json" },
		});
	};

	return (
		<>
			<Head>
				<title>iGive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<style>
					@import
					url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
				</style>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
				></link>
			</Head>
			<Navbar />
			<div className={styles.container}>
				<h1>Fill in your details below...</h1>
				<div className={styles.form}>
					<form encType="multipart/form-data" method="post" action="/users">
						<label className={styles.label}>First Name</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your first name..."
							name="first_name"
							type="text"
							value={firstName}
							onChange={(e) => setFirstName(e.target.value)}
						></textarea>
						<label className={styles.label}>Last Name</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your last name..."
							name="last_name"
							type="text"
							value={lastName}
							onChange={(e) => setLastName(e.target.value)}
						></textarea>
						<label className={styles.label}>Address</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your address..."
							name="address"
							type="text"
							value={address}
							onChange={(e) => setAddress(e.target.value)}
						></textarea>
						{/* <label className={styles.label}>Contact Number</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your contact number..."
							value={contactNumber}
						></textarea> */}
						<label className={styles.label}>Email</label>
						<textarea
							className={styles.textField}
							placeholder="Enter your email..."
							name="email"
							type="text"
							value={email}
							onChange={(e) => setEmail(e.target.value)}
						></textarea>
						<input type="file" onChange={handleFileInputChange}></input>
					</form>
					{/* 'Inline If with Logical && Operator' (to conditionally render preview) */}
					{previewSource && (
						<img src={previewSource} style={{ height: "300px" }}></img>
					)}
					<Button handleSubmit={handleSubmit} text="Submit" />
				</div>
			</div>
		</>
	);
}

export default Register;

//max chars for item description is 180
